title: "Purvaash P U"
author: "Purvaash P U"
description: "Purvaash Panduranghan Udhayashankar"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/index.md", title: "Home"}
  - {file: "/upload_cv.pdf", title: "CV"}
  - {file: "/README.md", title: "Readme"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:purvaash.panduranghan-udhayashankar@weizmann.ac.il"}
  - {title: Github, icon: github, url: "https://github.com/purvaash"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/purvaash-p-u-709244277/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
